# Generated by Django 3.2.7 on 2022-04-01 11:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
