# Generated by Django 4.0.3 on 2022-04-07 06:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220401_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
